# Generated by Django 5.1.1 on 2026-03-25 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_cookinglog_note_cookinglog_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('category', models.CharField(blank=True, max_length=64)),
                ('default_unit', models.CharField(default='item', max_length=32)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('meal', models.CharField(default='Dinner', max_length=32)),
                ('summary', models.TextField(blank=True)),
                ('cook_time_minutes', models.PositiveIntegerField(default=20)),
                ('servings', models.PositiveIntegerField(default=2)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('instructions', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(default='item', max_length=32)),
                ('storage', models.CharField(default='Fridge', max_length=64)),
                ('purchased_on', models.DateField(blank=True, null=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pantry_items', to='dashboard.ingredient')),
            ],
            options={
                'ordering': ['expires_on', 'ingredient__name', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(default='item', max_length=32)),
                ('is_optional', models.BooleanField(default=False)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_links', to='dashboard.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='dashboard.recipe')),
            ],
            options={
                'ordering': ['recipe__name', 'ingredient__name'],
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
    ]
